version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
  bot:
    build: .
    env_file:
      - .env
    command: python telegram_bot.py