# Generated by Django 5.2 on 2025-04-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('allows_write_to_pm', models.BooleanField(default=False)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('auth_date', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=255)),
            ],
        ),
    ]
