# Generated by Django 5.2 on 2025-04-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('telegram_id', models.CharField(max_length=50)),
                ('telegram_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True)),
                ('session', models.JSONField()),
            ],
        ),
    ]
