# Generated by Django 5.2 on 2025-04-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='id',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='telegram_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
