# Generated by Django 5.2 on 2025-04-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userlogin_id_alter_userlogin_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='session',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
